### ISSUE TITLE
Feature request: Allow for smiley too

### ISSUE THREAD

**Issue by japhir** [duckwork/frowny.el#1]
Typing `:)` would be a nice addition!

**Comment by duckwork** [comment]
Is there a use-case for this?  As far as I know, modes like `electric-pair-mode` only insert an extra (unwanted) closing pair when typing the open bracket -- so `:)` should be typable without intervention.

**Comment by alphapapa** [comment]
Now, come on, there's clearly more duckwork to be done here: What if I want to type a smiley inside a set of parens, like (with `|` representing point):
```
I found a new package today called `frowny` (which, despite its name, brings a :|)
```
If I then insert a `)`, `electric-pair-mode` will skip past the `)`, leaving me with `brings a :)|`--and then the `)` has to serve double-duty as both the mouth and closing paren, which isn't fair at all.  It should clearly be `brings a :)|)` or `brings a :) |)`.

The only question is whether this feature could possibly be considered in-scope for this package, given its name...

**Comment by d12frosted** [comment]
Off-topic. But I really need to say it - this package is amazing. Emacs community is amazing. You folks rock 💯 

Not I am going to grab a shield for a well deserved rock for off-topic. See you! ❤️

**Comment by alphapapa** [comment]
> Off-topic. But I really need to say it - this package is amazing. Emacs community is amazing. You folks rock 100

acdw certainly brought an "unfrowny" to my face.  :)

> Not I am going to grab a shield for a well deserved rock for off-topic. See you! heart

Nah, no rocks, we'll just slap you gently with a wet squirrel.  :)

**Comment by japhir** [comment]
> Is there a use-case for this?
Ah, I guess my issue isn't because of `electric-pair-mode` but because I'm using smartparens' `turn-on-smartparens-strict-mode`. So when I try to type `:)` I get `:` and a message `We can not insert unbalanced closing delimiter in strict mode.`

**Comment by d12frosted** [comment]
@alphapapa had to show off my editing skills:

![d7043aa5e46fc3062b6e4bc6c8d7c183](https://user-images.githubusercontent.com/6507913/135273646-14ee72fc-6f83-4544-aad9-6611f258acf3.jpg)

**Comment by alphapapa** [comment]
@d12frosted LOL, quite the Gimpmaster you must be.  :)

**Comment by duckwork** [comment]
Damn, yall are right about this.  Okay, I'll include it in frowny -- expect an update later tonight!

(No, I won't make a new `smiley` package, because that's just *silly* :P )

**Comment by alphapapa** [comment]
> (No, I won't make a new `smiley` package, because that's just _silly_ :P )

Well, that, and @tarsius might get the wrong idea...  ;)
